import { useState } from "react";
import { CulturalCard, CulturalCardContent, CulturalCardHeader, CulturalCardTitle, CulturalCardDescription } from "@/components/ui/cultural-card";
import { CulturalButton } from "@/components/ui/cultural-button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ArrowLeft, User, MapPin, Phone, Heart, Share2, BookOpen, Languages, Clock, Star } from "lucide-react";
import { toast } from "sonner";

interface Product {
  id: string;
  title: string;
  description: string;
  price: number;
  images: string[];
  is_featured: boolean;
  is_festival_special: boolean;
  profiles: {
    name: string;
    region: string;
    phone: string;
  };
  artforms: {
    name: string;
    description: string;
    region: string;
    cultural_significance: string;
    history: string;
    heritage_story: string;
  };
}

interface ProductDetailProps {
  product: Product;
  onBack: () => void;
}

export function ProductDetail({ product, onBack }: ProductDetailProps) {
  const [selectedImage, setSelectedImage] = useState(0);
  const [showCulturalStory, setShowCulturalStory] = useState(false);
  const [language, setLanguage] = useState<'english' | 'hindi'>('english');

  const getArtformEmoji = (artformName: string) => {
    const emojiMap: Record<string, string> = {
      'madhubani painting': '🎨',
      'warli art': '🏺',
      'block printing': '🧵',
      'pottery': '⚱️',
      'embroidery': '🪡',
    };
    return emojiMap[artformName.toLowerCase()] || '🎨';
  };

  const handleContact = () => {
    if (product.profiles.phone) {
      window.open(`tel:${product.profiles.phone}`, '_blank');
    } else {
      toast.success("Contact information saved to your favorites!");
    }
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: product.title,
        text: `Check out this beautiful ${product.artforms.name} by ${product.profiles.name}`,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast.success("Link copied to clipboard!");
    }
  };

  // Mock cultural story translations
  const getCulturalContent = () => {
    if (language === 'hindi') {
      return {
        significance: product.artforms.cultural_significance + " (Hindi translation would be generated by AI)",
        history: product.artforms.history + " (Hindi translation would be generated by AI)",
        heritage: product.artforms.heritage_story + " (Hindi translation would be generated by AI)"
      };
    }
    return {
      significance: product.artforms.cultural_significance,
      history: product.artforms.history,
      heritage: product.artforms.heritage_story
    };
  };

  const culturalContent = getCulturalContent();

  return (
    <div className="min-h-screen bg-gradient-heritage">
      {/* Header */}
      <header className="bg-card/90 backdrop-blur-md shadow-cultural border-b border-border sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <CulturalButton variant="ghost" onClick={onBack} className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Marketplace
            </CulturalButton>
            
            <div className="flex items-center gap-2">
              <CulturalButton variant="ghost" size="sm" onClick={handleShare}>
                <Share2 className="w-4 h-4" />
              </CulturalButton>
              <CulturalButton variant="ghost" size="sm">
                <Heart className="w-4 h-4" />
              </CulturalButton>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Product Images */}
          <div className="space-y-4">
            <CulturalCard variant="artisan">
              <CulturalCardContent className="p-0">
                <img
                  src={product.images[selectedImage] || '/api/placeholder/600/400'}
                  alt={product.title}
                  className="w-full h-96 object-cover rounded-lg"
                />
              </CulturalCardContent>
            </CulturalCard>
            
            {product.images.length > 1 && (
              <div className="flex gap-2 overflow-x-auto">
                {product.images.map((image, index) => (
                  <img
                    key={index}
                    src={image}
                    alt={`${product.title} view ${index + 1}`}
                    className={`w-20 h-20 object-cover rounded cursor-pointer border-2 ${
                      selectedImage === index ? 'border-primary' : 'border-transparent'
                    }`}
                    onClick={() => setSelectedImage(index)}
                  />
                ))}
              </div>
            )}
          </div>

          {/* Product Details */}
          <div className="space-y-6">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <span className="text-3xl">{getArtformEmoji(product.artforms.name)}</span>
                <div className="flex gap-2">
                  {product.is_featured && (
                    <Badge variant="secondary">
                      <Star className="w-3 h-3 mr-1" />
                      Featured
                    </Badge>
                  )}
                  {product.is_festival_special && (
                    <Badge variant="outline" className="border-orange-300 text-orange-600 bg-orange-50">
                      Festival Special
                    </Badge>
                  )}
                </div>
              </div>
              
              <h1 className="text-3xl font-cultural text-primary mb-2">{product.title}</h1>
              <p className="text-lg text-muted-foreground mb-4">{product.description}</p>
              
              {product.price && (
                <div className="text-2xl font-bold text-primary mb-4">
                  ₹{product.price.toLocaleString()}
                </div>
              )}
            </div>

            <Separator />

            {/* Artform Info */}
            <CulturalCard variant="heritage">
              <CulturalCardHeader>
                <CulturalCardTitle className="flex items-center gap-2">
                  {getArtformEmoji(product.artforms.name)}
                  {product.artforms.name}
                </CulturalCardTitle>
                <CulturalCardDescription>
                  {product.artforms.description}
                </CulturalCardDescription>
              </CulturalCardHeader>
            </CulturalCard>

            {/* Artisan Info */}
            <CulturalCard variant="artisan">
              <CulturalCardContent className="p-4">
                <div className="flex items-center gap-3 mb-3">
                  <span className="text-2xl">👨‍🎨</span>
                  <div>
                    <h3 className="font-semibold">Meet the Artisan</h3>
                    <p className="text-sm text-muted-foreground">Master craftsperson</p>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <User className="w-4 h-4 text-muted-foreground" />
                    <span className="font-medium">{product.profiles.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-muted-foreground" />
                    <span>{product.profiles.region}</span>
                  </div>
                  {product.profiles.phone && (
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4 text-muted-foreground" />
                      <span>{product.profiles.phone}</span>
                    </div>
                  )}
                </div>
                
                <CulturalButton 
                  variant="cultural" 
                  className="w-full mt-4"
                  onClick={handleContact}
                >
                  <Phone className="w-4 h-4 mr-2" />
                  Contact Artisan
                </CulturalButton>
              </CulturalCardContent>
            </CulturalCard>

            {/* Cultural Story Section */}
            <CulturalCard variant="timeline">
              <CulturalCardHeader>
                <div className="flex items-center justify-between">
                  <CulturalCardTitle className="flex items-center gap-2">
                    <BookOpen className="w-5 h-5" />
                    Cultural Heritage & Story
                  </CulturalCardTitle>
                  <div className="flex items-center gap-2">
                    <CulturalButton
                      variant={language === 'english' ? 'heritage' : 'ghost'}
                      size="sm"
                      onClick={() => setLanguage('english')}
                    >
                      English
                    </CulturalButton>
                    <CulturalButton
                      variant={language === 'hindi' ? 'heritage' : 'ghost'}
                      size="sm"
                      onClick={() => setLanguage('hindi')}
                    >
                      हिंदी
                    </CulturalButton>
                  </div>
                </div>
              </CulturalCardHeader>
              
              <CulturalCardContent>
                {!showCulturalStory ? (
                  <div className="text-center py-6">
                    <Clock className="w-12 h-12 text-primary mx-auto mb-4 animate-heritage-glow" />
                    <h3 className="font-semibold mb-2">Discover the Heritage</h3>
                    <p className="text-muted-foreground mb-4">
                      Learn about the rich cultural significance, history, and stories behind this beautiful artform
                    </p>
                    <CulturalButton 
                      variant="festival" 
                      onClick={() => setShowCulturalStory(true)}
                      className="gap-2"
                    >
                      <BookOpen className="w-4 h-4" />
                      Know More
                    </CulturalButton>
                  </div>
                ) : (
                  <div className="space-y-6 animate-cultural-fade">
                    <div>
                      <h4 className="font-semibold mb-2 flex items-center gap-2">
                        <Star className="w-4 h-4 text-primary" />
                        Cultural Significance
                      </h4>
                      <p className="text-sm leading-relaxed">{culturalContent.significance}</p>
                    </div>
                    
                    <Separator />
                    
                    <div>
                      <h4 className="font-semibold mb-2 flex items-center gap-2">
                        <Clock className="w-4 h-4 text-primary" />
                        Historical Background
                      </h4>
                      <p className="text-sm leading-relaxed">{culturalContent.history}</p>
                    </div>
                    
                    <Separator />
                    
                    <div>
                      <h4 className="font-semibold mb-2 flex items-center gap-2">
                        <BookOpen className="w-4 h-4 text-primary" />
                        Heritage Story
                      </h4>
                      <p className="text-sm leading-relaxed">{culturalContent.heritage}</p>
                    </div>
                    
                    {language === 'hindi' && (
                      <div className="bg-orange-50 border border-orange-200 rounded-lg p-3 mt-4">
                        <p className="text-xs text-orange-700">
                          <Languages className="w-3 h-3 inline mr-1" />
                          AI-generated Hindi translation - Cultural nuances preserved
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </CulturalCardContent>
            </CulturalCard>
          </div>
        </div>
      </main>
    </div>
  );
}