// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaurxevbfmkgdvjdwmdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdXJ4ZXZiZm1rZ2R2amR3bWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTc2OTgsImV4cCI6MjA3MzkzMzY5OH0._UDp32rscoa3HCcDu466Syp2yELbQP23CF6X2qGX1Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});